const API_PREFIX = '/api';

const ROUTES = {
  HEALTH: '/health',
  PING: '/ping',
  AUTH: '/auth',
  USERS: '/users',
  ROLES: '/roles',
  PRODUCTS: '/products',
  CATEGORIES: '/categories',
  PRODUCT_VARIANTS: '/product-variants',
  TAGS: '/tags',
  INVENTORY_BATCHES: '/inventory-batches',
  RELATED_PRODUCTS: '/related-products',
  SEARCH: '/search',
  ANALYTICS: '/analytics',
  ORDERS: '/orders',
  INVOICES: '/invoices',
  COUPONS: '/coupons',
  ORGANIZATIONS: '/organizations',
  CUSTOMERS: '/customers',
  CUSTOMER_GROUPS: '/customer-groups',
  CUSTOMER_ADDRESSES: '/customer-addresses',
  QUOTES: '/quotes',
  REVIEWS: '/reviews',
  WISHLIST: '/wishlist',
  PRICE_LISTS: '/price-lists',
  SCHEDULED_PRICES: '/scheduled-prices',
  BULK_PRICE_TIERS: '/bulk-price-tiers',
  ORDER_COMMENTS: '/order-comments',
  PRODUCT_COMMENTS: '/product-comments',
  ORDER_APPROVALS: '/order-approvals',
  REPORT_SCHEDULES: '/report-schedules',
  LOGS: '/logs',
  NOTIFICATIONS: '/notifications',
  ALERT_RULES: '/alert-rules',
  REPORTS: '/reports',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  API_KEYS: '/api-keys',
  WEBHOOKS: '/webhooks',
  BULK: '/bulk',
};

module.exports = {
  API_PREFIX,
  ROUTES,
};
